SignIn
YourHomeIsMine/react-yhim pull request #4
Opened 2023-03-01 13:44 UTC by tanonkim

### PR Type

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 기타

### 해당 PR의 목적

-

### 중점적으로 봤으면 하는 부분

-

2023-03-02 08:19 UTC, tanonkim commented on src/pages/SignUp/TextForm.tsx
> +};
이 부분 어떻게 구현되나요?

2023-03-02 10:41 UTC, hyejin30 requested changes

2023-03-02 10:41 UTC, hyejin30 commented on src/Router.tsx
> +import SignUp from 'pages/SignUp/SignUp';
파일명을 index.tsx로 했다면
SignUp 1개만 써두 됩니당!

2023-03-02 10:41 UTC, hyejin30 commented on src/Config.ts
> +export default API;
config.ts 파일 대신
.env 파일을 만들면 매번 import를 안해도 돼서
좋은데 활용 방법을 따로 알려드릴게요!

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +            break;
자바스크립트 구조분해할당 문법을 사용하면
아래처럼 코드를 줄일 수 있습니다!
키랑 값이 같으면 값을 생략할 수 있어요

```typescript
const { email, password, nickname, birthdate} = signUpInfo;

body : {
    email,
    password,
    nickname,
    birthdate,
}
```

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +      }
early return 패턴을 사용해보세요!

else if, else를 사용하지 않는 방식인데,
빨리 리턴 시키면 나머지 조건문까지 굳이 계산을 안해도 되는 효과가 있습니다.

```
if (조건) return ...
if (조건) return ...
```

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +    fetch(API.signup, {
이벤트 타입 선언 굳굳 👍

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +        if (result.message === 'User Created!') {
개인적인 의견인데
이용 약관은 Policy 로 해보면 어떨까 해요~!
Term이 처음에는 단어인가? 뜻이 헷갈렸었어요

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +        if (result.message === 'User Created!') {
form 안에 또 form이 있는 구조는 
시맨틱하지 않은 것 같아요!
부모 form은 div로 바꿔도 무방할 것 같습니다

2023-03-02 10:41 UTC, hyejin30 commented on src/pages/SignUp/Textform/TextFormContainer.tsx
> +const TextFormContainer = ({ data, change }: signUpInfo) => {
Container라는 이름 보다
아래 2가지 방향으로 생각해보면 좋을 것 같아요!

저는 보통 여러개 있으면 -List 라고 짓거나
역할을 강조하는 편이에요

1. 폼이 여러개 있다
FormList
TextFormList

2. 무슨 역할인지 강조
UserInfoForm
SignUpForm

2023-03-02 10:45 UTC, hyejin30 requested changes

2023-03-02 10:45 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +        </form>
form 안에 또 form이 있는 구조는 
시맨틱하지 않은 것 같아요!
부모 form은 div로 바꿔도 무방할 것 같습니다

2023-03-02 13:17 UTC, tanonkim commented on src/Router.tsx
> +import SignUp from 'pages/SignUp/SignUp';
index의 의도대로 사용하기 위해 파일명을 변경했습니다!

2023-03-02 13:18 UTC, tanonkim commented on src/Config.ts
> +export default API;
네, 확인했습니다.

2023-03-02 22:13 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +      </fieldset>
fieldset 왜 썼는지 이유를 설명해주세요!
저는 처음 봐서 질문 드립니다!

2023-03-02 22:13 UTC, hyejin30 commented on src/pages/SignUp/Textform/UserInfoForm.tsx
> +      <TextForm
Form은 인풋 여러개 있는 태그를 말하는데
TextInput 이라고 하는게 더 낫지 않을까 싶습니다!
form 태그를 리턴한다고 혼동할 수 있을 것 같습니다.

TextForm으로 그대로 유지 하신다면
이유를 적어주시면 참고하겠습니다

2023-03-02 22:13 UTC, hyejin30 commented on src/pages/SignUp/Textform/UserInfoForm.tsx
> +      </BirthContainer>
birthDate도 handleChange에서 처리하도록 수정했기 때문에
생년월일 입력하는 인풋도
TextInput 재사용할 수 있을 것 같아요

2023-03-02 22:13 UTC, hyejin30 commented on src/utils/regex.ts
> +// HJ: 정규식 패턴들은 파일에 따로 뺴놓는게 관리하기 좋습니당!
정규식 패턴들은 파일에 따로 빼 놓는게 관리하기 편해서
유틸 폴더에 따로 뺐습니다.

2023-03-02 22:19 UTC, hyejin30 commented on src/utils/convertDate.ts
> +};
1. useRef
이 훅은 값이 변해도 리렌더링이 안되도록 하고 싶거나, 
dom 태그 선택할 때 쓰는 hook인데
생년월일 하이픈 붙일 때 사용하면 코드가 복잡해지는 것 같다고 느껴졌어요

2. 개인적인 의견인데 리액트에서 for문은 지양하는 걸 추천드립니다!
리액트가 명령형이 아닌 선언형 언어라서 (필요한 거 바로 쓰는st)
forEach, map 같은 반복 함수들을 주로 활용하는 편입니다.

이런 이유로 정규식 패턴 활용해서 수정해봤는데
편하신 방법으로 선택 부탁드립니다

참고글 : https://velog.io/@nemo/%EC%84%A0%EC%96%B8%ED%98%95-%EB%AA%85%EB%A0%B9%ED%98%95

2023-03-02 22:19 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +  };
handleBirth를 위처럼 리팩토링 했습니다.
주석 참고해주세요!

2023-03-02 22:19 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +// HJ: prettier 에 importOrder를 추가했습니다. 필요한 것들은 더 추가해서 쓰세요!
prettierrc.js 파일에 importOrder를 추가했습니다.
저장할 때마다 설정해놓은 순서대로 임포트가 자동 정렬됩니다.

트리바고에서 쓰는 플러그인 설치해야 적용돼서
플러그인 설치했습니다. 참고해주세요!
https://github.com/trivago/prettier-plugin-sort-imports

2023-03-02 22:19 UTC, hyejin30 commented on src/pages/SignUp/Textform/UserInfoForm.tsx
> +}
props가 있을 때 타입은 위처럼 작성하면 됩니다
주석 참고해주세요!

2023-03-02 22:20 UTC, hyejin30 commented on src/utils/regex.ts
> +  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/;
정규식 패턴들은 파일에 따로 빼놓는게 관리하기 편해서
utils/regex.ts 를 만드셔서 관리하는 걸 추천드려요!

2023-03-02 22:25 UTC, hyejin30 commented on src/types/env.d.ts
> +}
env.ts 파일의 타입을 선언할 수 있습니다.
이렇게 하면 
process.env 를 칠 때 key 값들이 목록에 뜨게 돼서 편해요

<img width="451" alt="image" src="https://user-images.githubusercontent.com/98295004/222572865-9dc58be4-3d44-4754-8bfe-b332adf44ac1.png">

2023-03-02 22:25 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +      `${process.env.REACT_APP_API_ADDRESS}/users/signup`,
1. config 대신 .env 파일을 사용할 수 있을 것 같아요~!
.env 파일은 gitignore에 추가해서 깃헙에 올라가지 않는 파일입니다. 주소 숨기고 싶을 때 좋고, import 없이 전역에서 사용 가능합니다.

2. REACT_APP_을 앞에 붙여야 브라우저에서 사용가능하고,
붙이지 않으면 node.js 환경에서만 사용 가능합니다.
사용자에게 노출되어도 괜찮은 값은 REACT_APP_을 꼭 붙여주세요

3. users/signup 을 변수로 만들어서 관리하지 않아도 괜찮을 것 같아요! 여러명이서 같이 작업한다고 가정한다면,
config 파일을 여러명이 동시에 수정하게 돼서 컨플릭트를 유발할 수 있을 것 같습니다.

2023-03-02 22:25 UTC, hyejin30 commented on .gitignore
> +.env
.env는 올라가지 않도록 꼭 추가해주세요!

2023-03-02 22:29 UTC, hyejin30 commented on src/pages/SignUp/UserInfoForm/index.tsx
>  }
props가 있을 때 타입은 위처럼 작성하면 됩니다
주석 참고해주세요!

2023-03-02 22:29 UTC, hyejin30 commented on src/pages/SignUp/SignUp.tsx
> +import UserInfoForm from './UserInfoForm';
폴더/index.tsx 로 이름 짓는 걸 추천드립니다
/TermForm/TermForm
-> /TermForm
이렇게 한번만 적을 수 있습니다~

2023-03-02 23:59 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +      }
오~ 확인했습니다!

2023-03-03 00:06 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +        if (result.message === 'User Created!') {
수정 완료했습니다!

2023-03-03 00:27 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +        </form>
네~ 확인했습니다!

2023-03-03 00:36 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +      </fieldset>
`form`요소에서 연관된 요소들을 하나의 그룹으로 사용하기 위함입니다.
여기선f`fieldset`이 가지는 속성(legend)을 사용하지 않았기 때문에  'div'와 크게 의미차이가 나진 않습니다.

2023-03-03 00:45 UTC, tanonkim commented on src/pages/SignUp/Textform/UserInfoForm.tsx
> +      <TextForm
말씀하신 대로 `Input`을 사용하는게 더 적절한 것 같습니다! 
반영하여 수정했습니다!

2023-03-03 00:51 UTC, tanonkim commented on src/pages/SignUp/Textform/UserInfoForm.tsx
> +      </BirthContainer>
저도 재사용성과 관련해서 고민을 했는데
`if (name === 'birthDate') return handleBirthDate(value);` 이 코드를 사용하면서 해결되네요!

2023-03-03 01:05 UTC, tanonkim commented on src/utils/convertDate.ts
> +};
1. 정규식 패턴활용이 더 나은 것 같습니다. 굳이 `useRef`와 for문을 돌리는 것보다 더 간결하고 더 명확하네요!
2. 앞으로 리액트의 특징대로 선언형으로 작성하겠습니다.
3. 참고글이 많이 도움되었습니다. 덕분에 잘 정리가 되었어요!

2023-03-03 01:06 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +  };
네! 확인했습니다

2023-03-03 01:09 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +// HJ: prettier 에 importOrder를 추가했습니다. 필요한 것들은 더 추가해서 쓰세요!
네! 감사합니다 :)

2023-03-03 01:14 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
>    });
네! `birthDate` 필드에 함수가 들어가서 분리한 것 때문에 고민이 있었는데 하나로 관리하는게 더 나은 것 같습니다.

`handleChange`, `handleBirth` 함수 확인했습니다!

2023-03-03 01:20 UTC, tanonkim commented on src/utils/regex.ts
> +  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/;
네! 앞으로 정규식은 다음과 같이 관리하겠습니다!

2023-03-03 02:03 UTC, tanonkim commented on src/types/env.d.ts
> +}
네! 확인했습니다 :)

2023-03-03 02:29 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +      `${process.env.REACT_APP_API_ADDRESS}/users/signup`,
1. env 환경변수 활용도 좋은 방법이네요!
2. 네 확인했습니다. 추가로 `.env.development`(개발환경),`.env.production`(배포) 처럼 활용도 가능하겠네요!
3. 네! 환경변수로 관리하도록 하겠습니다

2023-03-03 02:32 UTC, tanonkim commented on src/pages/SignUp/UserInfoForm/index.tsx
>  }
네! 감사합니다 👍

2023-03-03 02:38 UTC, tanonkim commented on src/pages/SignUp/SignUp.tsx
> +import UserInfoForm from './UserInfoForm';
오! 네, 확인했습니다.

2023-03-04 05:08 UTC, tanonkim commented on src/pages/SignUp/Textform/TextFormContainer.tsx
> +const TextFormContainer = ({ data, change }: signUpInfo) => {
네, 확실히 List와 역할로 강조하니 제가 다시 코드를 볼 때도, 협업할 때도 수월하게 할 수 있겠네요!
말씀해주신대로 변경했습니다.

2023-03-06 12:04 UTC, merged