Main Page
YourHomeIsMine/react-yhim pull request #6
Opened 2023-03-05 06:33 UTC by tanonkim

### PR Type

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 기타

### 해당 PR의 목적

- 메인 화면

### 중점적으로 봤으면 하는 부분

-

2023-03-05 06:35 UTC, tanonkim commented
Merge 이전이라, 이전의 커밋들이 남아있습니다.

[fccaa92] @tanonkim
[Feature: Add productList with fetch url](https://github.com/YourHomeIsMine/react-yhim/pull/6/commits/fccaa922cc4fa03fae529480fee439282d26a9e5)
해당 커밋부터 봐주시면 감사하겠습니다!

2023-03-06 13:09 UTC, hyejin30 requested changes
리뷰 반영해주세요~

2023-03-06 13:09 UTC, hyejin30 commented on src/pages/Main/index.tsx
> +            // handleClick={handleClick}
props를 개별로 다 써주지 않고
하나만 써줘도 좋을 것 같습니다~~
```typescript
<Card
    product={product}
/>
```

2023-03-06 13:09 UTC, hyejin30 commented on src/pages/Main/Card/index.tsx
> +};
1. 컴포넌트명은 Card 보다 `ProductInfo` 또는 `Product` 가 더 적절할 것 같습니다.

2. 지금은 타입 에러가 발생할 것 같아요.
    컴포넌트가 전달받는 값들의 타입을 다 기재해주셔야 됩니다!
    types 에 d.ts 파일 만들어서 타입을 선언해주세요

```
type ProductType = {
  room_name : ...;
  price : ...;
  // 그 외 값들
}
```

3. Product 컴포넌트에 `product`만 넘긴다고 가정했을 때, 아래처럼 리팩토링 가능합니다.
```typescript
// Main/index.tsx
<Product
    product={product}
/>
```
```typescript
// Product/index.tsx 

interface ProductProps {
  product: ProductType
}

const Product = ({
  room_name,
  price,
  address,
  images,
  category,
  guest,
  id,
  schedule,
} : ProductProps) => {
  return <div>Product</div>;
};
```

2023-03-06 13:09 UTC, hyejin30 commented on src/pages/Main/index.tsx
> +  });
지금은  productList 값 변경 유무와 상관 없이 렌더링 할 때 마다 productList가 콘솔에 찍히게 되는데,
productList 값이 변경될 때마다 값을 보고 싶다면
depency에 productList를 추가해주면 좋아요

```typescript
useEffect(() => {
    console.log(productList);
  }, [productList]); // <-- 추가
```

2023-03-06 13:19 UTC, hyejin30 commented on src/pages/Main/index.tsx
> +            // handleClick={handleClick}
함수는 prop으로 내려줄 때 꼭 on을 앞에 붙여주세요~~
```
onClick={handleClick}
```

2023-03-06 15:54 UTC, tanonkim commented on src/Router.tsx
> +          <Route path="/" element={<Main />} />
Conflict 해결하면서 해결했습니다!

2023-03-06 15:59 UTC, tanonkim commented on src/pages/Main/index.tsx
> +  }, [handleScroll]);
네! 확인했습니다 :)

2023-03-06 16:15 UTC, tanonkim commented on src/pages/Main/index.tsx
> +            // handleClick={handleClick}
props를 하나로 수정사항 반영했습니다!

2023-03-06 16:36 UTC, tanonkim commented on src/pages/Main/index.tsx
> +            // handleClick={handleClick}
확인했습니다!!

2023-03-06 16:38 UTC, tanonkim commented on src/pages/Main/index.tsx
> +  });
네, 확인했습니다!
`useEffect`는 확인용으로 삭제 했습니다!

2023-03-07 14:06 UTC, tanonkim commented on src/pages/Main/Card/index.tsx
> +};
1. 여러 코드를 분석해보았을 때 리스트의 이름이 Card 형태로 많이 되어있어 Card 형태의 리스트 이름으로 사용했다고 이해했습니다!
    데이터 값들이 달라 공통 컴포넌트로 사용하기 어렵다고 판단되어 `ProductInfo`로 변경하였습니다.
2. `npx tsc --watch`로 타입 확인해보았습니다!
4. 네! 이전에 만들어두었던 타입을 활용했습니다.
5. 말씀해 주신 부분이랑 구조분해 할당을 통해 리팩토링을 완료했습니다!

리뷰 감사합니다 :)

2023-03-07 14:06 UTC, merged