Detail page
YourHomeIsMine/react-yhim pull request #8
Opened 2023-03-09 00:46 UTC by tanonkim

### PR Type

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 기타

### 해당 PR의 목적

- Detail Page

### 중점적으로 봤으면 하는 부분

-

2023-03-10 13:35 UTC, hyejin30 commented
[UI 수정 사항] -> [4af2b6c](https://github.com/YourHomeIsMine/react-yhim/pull/8/commits/4af2b6c4de6fb9b227db0be12d07f4c242bad2f2)

1. 화면 축소 했을 때 요소들이 1440px까지만 늘어나도록
WrapperLayout에 max-width: 1440px 적용해주었어요

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/98295004/224329024-0c3c7399-a99b-4643-8d18-a2914b8755f5.png">

2. 그리고 꼭 css가 필요하지 않다면 쓰지 않는 걸 권장해요~!
- flex 적용하게 되면 부모 본인, 자식들의 css가 많이 바뀌게 돼서
  flex가 꼭 필요할 때만 써주세요!

2023-03-10 14:38 UTC, hyejin30 requested changes

2023-03-10 14:38 UTC, hyejin30 commented on src/pages/Detail/index.tsx
> +`;
Container에 padding-top: 40%를 주면
아래처럼 화면을 확대 했을 때 여백이 크게 남습니다.

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/98295004/224337605-2c332f2c-359c-40c9-b8a3-b57bdd9dd6e2.png">

Header에 콘텐츠가 가려지는걸 방지하려면
Layout에서 Body 태그를 만들어서
padding을 (top, bottom만) 공통으로 주고 시작하는 방법을 추천합니다.

```typescript
const Layout = () => {
  return (
    <Container>
      <Header />
      <Body>
        <WrapperLayout>
          <Outlet />
        </WrapperLayout>
      </Body>
      <Footer />
    </Container>
  );
};

const Body = styled.div`
  padding: 120px 0;
`;
```

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/98295004/224339468-e2537363-2e5e-4c77-92ed-a9c85ca5fba4.png">

DetailContainer에서 padding을 삭제하고 border 값만 줬을 때 화면입니다. 
Layout - Body에서 위 아래로 공통 padding을 줬기 때문에
페이지별로 padding을 매번 주지 않아도 됩니다~

```typescript
const DetailContainer = styled.div`
  border: 5px solid blue;
`;
```

2023-03-10 14:38 UTC, hyejin30 commented on src/pages/Detail/index.tsx
> +`;
컨텐츠 `안쪽 여백` 이므로 
margin 보다 padding이 적절할 것 같습니다.

margin : 컨텐츠 A와 B 간의 간격 (서로 같은 레벨인 요소 간의 간격)
padding : 컨텐츠 A의 여백 (부모-자식 간의 여백)

Wrapper를 삭제하고 Container만 남겨주세요~!
```typescript
const DetailContainer = styled.div`
  padding: 0 20px;
`;
```

2023-03-10 14:38 UTC, hyejin30 commented on src/pages/Detail/index.tsx
> +`;
이것도 Wrapper 까지 만들지 않아도 될 것 같아요!
ProductDescription에 위아래 padding을 주는게 더 적절할 것 같습니다.

```typescript
  return (
    <DetailContainer>
      <Header detailList={detailList} />
      <ProductImage image={room_images_url}></ProductImage>
      <ProductInfo detailList={detailList} />
      <ProductDescription>{description}</ProductDescription>
      <ProductAmenity room_amenities={room_amenities} />
    </DetailContainer>
  );
};

const ProductDescription = styled.div`
  padding: 40px 0;
  border-bottom: 1px solid ${colors.MEDIUMGRAY};
  ${font(18, 500, 22)};
  color: ${colors.BLACK};
`;
```

ProductDescription에 `border: 1px solid red`를 적용해서
padding, margin 차이를 적용해보면 아래와 같습니다.

padding: 40px 0;

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/98295004/224341866-0e2b86f2-8ee3-4117-8bb9-8c8fb2349b93.png">

margin: 40px 0;

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/98295004/224341958-5a2c8177-6364-48a8-9196-940dd2be43c5.png">

저는 Description이 텍스트 + 여백이 있는 한 영역으로 간주하고
padding을 쓰는 편입니다.

2023-03-10 14:38 UTC, hyejin30 commented on src/pages/Main/ProductInfo/index.tsx
> +    <Container onClick={() => handleClick(room_id)}>
- room_id를 이미 변수로 선언했기 때문에 함수 인자로 넘기지 않아도 될 것 같습니다.
- 클릭 했을 때 id가 생성되는게 아니기 때문에, 함수명도 goDetailPage 로 직관적으로 바꿔주어도 될 것 같아요

```typescript
const goDetailPage = () => {
    navigate(`/room/${room_id}`);
};

<Container onClick=(goDetailPage)>
```

2023-03-10 14:38 UTC, hyejin30 commented on src/pages/Main/ProductInfo/index.tsx
>    position: relative;
컴포넌트명이 ProductInfo 라서
이미 제품에 대해 다룰 것이라는 걸 알고 있습니다.
그래서 태그 명에 Product를 굳이 다 써줄 필요는 없을 것 같아요

2023-03-10 15:02 UTC, hyejin30 requested changes

2023-03-11 07:22 UTC, tanonkim commented on src/pages/Main/ProductInfo/index.tsx
> -  z-index: 100;
네, 부모 기준에 따라 px를 주면 되니, 이 방법으로 적용하겠습니다.

2023-03-12 02:23 UTC, tanonkim commented on src/pages/Detail/index.tsx
> +`;
제가 찾던 방법입니다. 디테일 화면의 컨텐츠가 생성될 때마다 하나씩 `padding`값을 변경해주었어야 했는데, 한번 더 감싸고 여기에 `padding`을 주니 해결이 쉽게 되네요!

적용 완료하였습니다.

2023-03-12 02:24 UTC, tanonkim commented on src/pages/Detail/index.tsx
> +`;
레이아웃 수정하면서 해당 `wrapper`는 삭제 완료했습니다.

2023-03-12 02:31 UTC, tanonkim commented on src/pages/Detail/index.tsx
> +`;
1. 셀프 클로징 전체 완료했습니다.
2. `Wrapper`의 의미에 맞게 사용하기 위해 삭제했고, `margin`보다는 `padding`이 적절해 수정해두었습니다.

2023-03-12 02:43 UTC, tanonkim commented on src/pages/Main/ProductInfo/index.tsx
> +    <Container onClick={() => handleClick(room_id)}>
🙌 질문이 있습니다. 

함수 파라미터의 id는 해당 Room의 인자값인 room_id가 들어와야 하므로, 함수인자로 넘기면서 인자값을 넣어줘야 할 것 같습니다. 즉 `<Container onClick={() => goDetailPage(room_id)}>` 이렇게 되어야 할 것 같아요!

2023-03-12 02:44 UTC, tanonkim commented on src/pages/Main/ProductInfo/index.tsx
>    position: relative;
네, 리뷰주신대로 수정사항 반영했습니다!

2023-03-12 02:46 UTC, tanonkim commented on src/pages/Detail/ProductAmenity/index.tsx
> +        <AmenityContent key={i} data={data}></AmenityContent>
1. 문자열과 같이 조합하기, 신경쓰겠습니다.
2. 수정사항 반영했습니다.

2023-03-12 03:48 UTC, tanonkim commented on src/pages/Detail/ProductAmenity/AmenityContent.tsx
> +  const { amenity_id, amenity_icon_url, amenity_name } = data;
any 타입 전체적으로 타입 반영했습니다!

2023-03-12 03:50 UTC, tanonkim commented on src/pages/Detail/ProductAmenity/index.tsx
> +      {room_amenities.slice(0, 10).map((data: AmenityProps, i: number) => (
1. 새로 타입을 선언했는데, 대신에 `AmenityType[]`타입으로 줄 수 있네요! 반영 완료했습니다.
2. `string[]`으로 선언해두었고 에러가 해결되지 않아 고민했었는데, 대신에 `AmenityType[]`으로 선언하니 간단하게 해결되네요! 수정완료했습니다.

2023-03-12 04:22 UTC, tanonkim commented on src/pages/Detail/ProductDetailInfo/index.tsx
> +  } = detailList;
선언 완료했습니다!

2023-03-14 13:18 UTC, hyejin30 commented on src/pages/Detail/Reservation/Price/index.tsx
> +
css 가 따로 없어서
그냥 div로 바꿔도 될 것 같아요

```
<div>
    <ReservationBtn>예약하기</ReservationBtn>
    ....
</div>
```

2023-03-14 13:31 UTC, hyejin30 commented on src/pages/Detail/Notice/index.tsx
> +        <NoticeContent key={`amenity-${i}}`} data={data} />
key 이름을 수정해주세요~

PR 올린 후에 file changed 보면서 
아래 4가지는 꼭 셀프 체크해주세요!

1. map 메소드 사용한 곳에 key를 넣었는지
2. key 이름을 잘 썼는지
3. props 이름을 잘 썼느지
4. 테스트용 console.log를 삭제했는지

2023-03-14 13:31 UTC, hyejin30 commented on src/pages/Detail/Notice/index.tsx
> +
css가 없는 태그는 그냥 div를 사용해주세요

2023-03-14 13:33 UTC, hyejin30 commented on src/pages/Detail/Map/index.tsx
> +  }, []);
useState, useCallback 등은 가독성을 위해서 
import 해서 써도 될 것 같습니다~~

import { useState, useCallback } from 'React'

2023-03-14 13:33 UTC, hyejin30 commented on src/pages/Detail/Map/index.tsx
> +      </GoogleMap>
구글 맵 api 연동 굿굿 👍

2023-03-14 13:48 UTC, hyejin30 commented on src/pages/Detail/index.tsx
> +`;
1. 부모 요소에 width : 65%, width: 35% 를 주지 않아도 됩니다

Calendar 컴포넌트에 있는 
const DateContainer의 width : 300px <- 이 수치만 원하는 수치로 기입하면 됩니다.

자식 요소에 고정 px을 이미 줬는데
부모 요소에 또 width % 를 줄 필요는 없을 것 같아요!
 
 2. position > width > margin 순으로
 css 속성 컨벤션에 맞게 다시 작성해주세요~!

2023-03-15 01:41 UTC, tanonkim commented on src/pages/Detail/Reservation/Price/index.tsx
> +        <div>₩{Number(data * 0.22).toLocaleString()}원</div>
1. `number`타입에 `number`타입으로 주었네요! 전반적으로 수정했습니다.
2. 변수 선언해서 반영완료했습니다.

2023-03-15 01:46 UTC, tanonkim commented on src/pages/Detail/Reservation/Price/index.tsx
> +
detail 페이지 내 전체적으로 사용하지 않는 styled 컴포넌트는 `div태그`로 변경했습니다.

2023-03-15 02:07 UTC, tanonkim commented on src/pages/Detail/Reservation/index.tsx
> +const Reservation = ({ data }: PriceProps) => {
수정 완료했습니다!

2023-03-15 02:08 UTC, tanonkim commented on src/pages/Detail/HostDetailInfo/index.tsx
> +            </HostSignUpDate>
split을 활용해서 구조분해 할당 완료했습니다. :)

2023-03-15 02:12 UTC, tanonkim commented on src/pages/Detail/HostDetailInfo/index.tsx
> +  //width: 50%;
삭제 완료했습니다!

2023-03-15 02:13 UTC, tanonkim commented on src/pages/Detail/HostDetailInfo/index.tsx
> +  text-align: center;
네, 앞으론 font 속성으로 관리하겠습니다.

2023-03-15 02:13 UTC, tanonkim commented on src/pages/Detail/Notice/index.tsx
> +
네, 수정 완료했습니다.

2023-03-15 02:17 UTC, tanonkim commented on src/pages/Detail/Map/index.tsx
> +  }, []);
오, 네 import로 선언했습니다.

2023-03-15 02:20 UTC, tanonkim commented on src/pages/Detail/Notice/index.tsx
> +        <NoticeContent key={`amenity-${i}}`} data={data} />
네, 확인했습니다! 셀프체크 반영하겠습니다 :)

2023-03-15 02:42 UTC, tanonkim commented on src/pages/Detail/index.tsx
> +`;
1. 자식에게 px를 주고, 부모에게 안줘도 될 width를 주고 있었네요. 수정 완료했습니다!
2. css 수정되면서 업데이트 완료해두었습니다.

2023-03-15 04:04 UTC, tanonkim commented on src/pages/Main/ProductInfo/index.tsx
> +    <Container onClick={() => handleClick(room_id)}>
네, 이미 `room_id`가 선언되어있으니, 인자값으로 넘길 필요가 없네요!
제가 다르게 생각했습니다.

2023-03-15 04:06 UTC, merged